
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=mysql
      - DB_PORT=3306
    volumes:
      # - ./backend:/app
      - ./backend/build/libs/backend-0.0.1-SNAPSHOT.jar:/app.jar

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: frontend
    environment:
      WATCHPACK_POLLING: true
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/vite.config.ts:/app/vite.config.ts

  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gawon
      MYSQL_USER: gawon
      MYSQL_PASSWORD: gawon
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysql -ugawon -pgawon -e 'SELECT 1'"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql-data:

